# Generated by Django 4.2.23 on 2025-07-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requester',
        ),
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
