# Generated by Django 4.2.23 on 2025-07-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_delete_requester_donor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='donor',
            name='gender',
            field=models.CharField(default='Other', max_length=10),
        ),
        migrations.AddField(
            model_name='donor',
            name='last_donation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
